services:
    ms_services.aside:
        class: MSServicesBundle\Service\ASideService
        arguments: ['@doctrine.orm.entity_manager']
        #arguments: ["@service_id", "plain_value", "%parameter%"]
