admin_post_index:
    path:     /
    defaults: { _controller: "MSAdminBundle:AdminPost:index" }
    methods:  GET

admin_post_show:
    path:     post/show/{id}
    defaults: { _controller: "MSAdminBundle:AdminPost:show" }
    methods:  GET

admin_post_new:
    path:     post/new
    defaults: { _controller: "MSAdminBundle:AdminPost:new" }
    methods:  [GET, POST]

admin_post_edit:
    path:     post/edit/{id}
    defaults: { _controller: "MSAdminBundle:AdminPost:edit" }
    methods:  [GET, POST]

admin_post_delete:
    path:     post/delete/{id}
    defaults: { _controller: "MSAdminBundle:AdminPost:delete" }
    methods:  DELETE
